[Writable]
LogLevel = "INFO"

[Service]
Port = 59711
StartupMsg = "RFID LLRP Inventory Service"

[Clients]
  [Clients.core-command]
  UseMessageBus = true
  [Clients.core-command.Topics]
  QueryRequestTopicPrefix = "edgex/core/commandquery/request"
  QueryResponseTopic = "edgex/core/commandquery/response"
  CommandRequestTopicPrefix = "edgex/core/command/request"
  CommandResponseTopic = "edgex/core/command/response/#"

[MessageBus]
  [MessageBus.Topics]
  SubscribeTopics = "edgex/events/+/device-rfid-llrp/+/+/ROAccessReport,edgex/events/+/device-rfid-llrp/+/+/ReaderEventNotification"
  PublishTopic="edgex/events/device/app-rfid-llrp/{profilename}/{devicename}/{sourcename}" # publish to same topic format the Device Services use
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
  ClientId ="app-rfid-llrp-inventory"

[Trigger]
# Note that the MessaegBus connection above is used by edgex-messagebus trigger
Type="edgex-messagebus"

[AppCustom]
  # Every device(reader) + antenna port represents a tag location and can be assigned an alias
  # such as Freezer, Backroom etc. to give more meaning to the data. The default alias set by
  # the application has a format of <deviceName>_<antennaId> e.g. Reader-10-EF-25_1 where
  # Reader-10-EF-25 is the deviceName and 1 is the antennaId.
  # See also: https://github.com/edgexfoundry/app-rfid-llrp-inventory#setting-the-aliases
  #
  # In order to override an alias, set the default alias as the key, and the new alias as the value you want, such as:
  # Reader-10-EF-25_1 = "Freezer"
  # Reader-10-EF-25_2 = "Backroom"
  [AppCustom.Aliases]

  # See: https://github.com/edgexfoundry/app-rfid-llrp-inventory#configuration
  [AppCustom.AppSettings]
  DeviceServiceName = "device-rfid-llrp"
  AdjustLastReadOnByOrigin = true
  DepartedThresholdSeconds = 600
  DepartedCheckIntervalSeconds = 30
  AgeOutHours = 336
  MobilityProfileThreshold = 6.0
  MobilityProfileHoldoffMillis = 500.0
  MobilityProfileSlope = -0.008
