[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48086
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'RFID LLRP Inventory Service'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic="events"

[ApplicationSettings]
DeviceServiceName = "edgex-device-rfid-llrp"
DeviceServiceURL = "http://localhost:51992/"
MetadataServiceURL = "http://localhost:48081/"
AdjustLastReadOnByOrigin = "true"
DepartedThresholdSeconds = "600"
DepartedCheckIntervalSeconds = "30"
AgeOutHours = "336"
MobilityProfileThreshold = "6"
MobilityProfileHoldoffMillis = "500"
MobilityProfileSlope = "-0.008"
