name: edgex-app-rfid-llrp-inventory
base: core20
license: Apache-2.0
summary: EdgeX RFID LLRP Inventory Application Service
description: Refer to https://snapcraft.io/edgex-app-rfid-llrp-inventory
adopt-info: app-rfid-llrp-inventory

architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, 
# 5: jakarta
epoch: 5

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/app-rfid-llrp-inventory]

plugs:
  app-rfid-llrp-inventory-config:
    interface: content
    target: $SNAP_DATA/config/app-rfid-llrp-inventory

  # deprecated
  app-config:
    interface: content
    target: $SNAP_DATA/config/app-rfid-llrp-inventory
 
apps:
  app-rfid-llrp-inventory:
    command: bin/app-rfid-llrp-inventory --configDir $SNAP_DATA/config/app-rfid-llrp-inventory/res --configProvider --registry
    command-chain:
      - bin/source-env-file.sh
    daemon: simple
    environment:
      SECRETSTORE_TOKENFILE: $SNAP_DATA/app-rfid-llrp-inventory/secrets-token.json
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  app-rfid-llrp-inventory:
    source: .
    plugin: make
    build-packages: [git]
    build-snaps:
      - go/1.20/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of the snap
      snapcraftctl set-version $VERSION

      # write version to file for the build
      echo $VERSION > VERSION

      make build

      install -DT "./app-rfid-llrp-inventory" "$SNAPCRAFT_PART_INSTALL/bin/app-rfid-llrp-inventory"
      
      RES=$SNAPCRAFT_PART_INSTALL/config/app-rfid-llrp-inventory/res
      mkdir -p $RES
      cp res/configuration.yaml $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-rfid-llrp-inventory
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

