name: edgex-app-rfid-llrp-inventory
base: core18
adopt-info: app-rfid-llrp-inventory
version: "replace-me"
version-script: |
  VERSION=$(shell cat ./VERSION 2>/dev/null || echo 0.0.0)
  echo $VERSION-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
  
license: Apache-2.0
title: EdgeX RFID LLRP Inventory
summary: EdgeX Application Service for inventory management
description: |
  Edgex application service for processing tag reads,
  producing events such as 'Arrived', 'Moved', 'Departed', configure and manage the LLRP readers via commands

# TODO: add armhf here when that's supported
architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

# delhi: 0, edinburgh: 1, fuji: 2, geneva: 3, ireland: 4, jakarta: 5
epoch: 5

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/app-rfid-llrp-inventory]

apps:
  app-rfid-llrp-inventory:
    adapter: full
    command: bin/app-rfid-llrp-inventory $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    daemon: simple
    environment:
      CONFIG_PRO_ARG: "-cp=consul.http://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/app-rfid-llrp-inventory/res"
      REGISTRY_ARG: "--registry"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/app-rfid-llrp-inventory/secrets-token.json
    passthrough:
      install-mode: disable
    plugs: [network, network-bind]

parts:
  app-rfid-llrp-inventory:
    source: .
    plugin: make
    build-packages: [gcc, git, libzmq3-dev, pkg-config]
    build-snaps:
      - go/1.17/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
        snapcraftctl set-version ${VERSION}
        # This is used in the Makefile:
        echo $VERSION > ./VERSION
      fi

      make build

      install -DT "./app-rfid-llrp-inventory" "$SNAPCRAFT_PART_INSTALL/bin/app-rfid-llrp-inventory"
      install -DT "./res/configuration.toml" \
         "$SNAPCRAFT_PART_INSTALL/config/app-rfid-llrp-inventory/res/configuration.toml"
      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-rfid-llrp-inventory/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-rfid-llrp-inventory/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  hooks:
    source: snap/local/hooks
    plugin: make
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"
