name: edgex-app-rfid-llrp-inventory
base: core20
adopt-info: metadata
license: Apache-2.0

architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, 
# 5: jakarta
epoch: 5

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/app-rfid-llrp-inventory]

plugs:
  app-rfid-llrp-inventory-config:
    interface: content
    target: $SNAP_DATA/config/app-rfid-llrp-inventory

  # deprecated
  app-config:
    interface: content
    target: $SNAP_DATA/config/app-rfid-llrp-inventory
 
apps:
  app-rfid-llrp-inventory:
    command: bin/app-rfid-llrp-inventory $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/source-env-file.sh
    daemon: simple
    environment:
      CONFIG_PRO_ARG: "-cp=consul://localhost:8500"
      CONF_ARG: "--configDir=$SNAP_DATA/config/app-rfid-llrp-inventory/res"
      REGISTRY_ARG: "--registry"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/app-rfid-llrp-inventory/secrets-token.json
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  app-rfid-llrp-inventory:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [gcc, git, libzmq3-dev, pkg-config]
    build-snaps:
      - go/1.20/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build

      install -DT "./app-rfid-llrp-inventory" "$SNAPCRAFT_PART_INSTALL/bin/app-rfid-llrp-inventory"
      
      RES=$SNAPCRAFT_PART_INSTALL/config/app-rfid-llrp-inventory/res
      mkdir -p $RES
      cp res/configuration.toml $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-rfid-llrp-inventory
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-app-rfid-llrp-inventory.metainfo.xml]
