//
// Copyright (C) 2020 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=VendorPEN,ImpinjModel -output vendors_string.go"; DO NOT EDIT.

package llrp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PENImpinj-25882]
	_ = x[PENAlien-17996]
	_ = x[PENZebra-10642]
}

const (
	_VendorPEN_name_0 = "PENZebra"
	_VendorPEN_name_1 = "PENAlien"
	_VendorPEN_name_2 = "PENImpinj"
)

func (i VendorPEN) String() string {
	switch {
	case i == 10642:
		return _VendorPEN_name_0
	case i == 17996:
		return _VendorPEN_name_1
	case i == 25882:
		return _VendorPEN_name_2
	default:
		return "VendorPEN(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpeedwayR220-2001001]
	_ = x[SpeedwayR420-2001002]
	_ = x[XPortal-2001003]
	_ = x[XArrayWM-2001004]
	_ = x[XArrayEAP-2001006]
	_ = x[XArray-2001007]
	_ = x[XSpan-2001008]
	_ = x[SpeedwayR120-2001009]
	_ = x[R700-2001052]
}

const (
	_ImpinjModel_name_0 = "SpeedwayR220SpeedwayR420XPortalXArrayWM"
	_ImpinjModel_name_1 = "XArrayEAPXArrayXSpanSpeedwayR120"
	_ImpinjModel_name_2 = "R700"
)

var (
	_ImpinjModel_index_0 = [...]uint8{0, 12, 24, 31, 39}
	_ImpinjModel_index_1 = [...]uint8{0, 9, 15, 20, 32}
)

func (i ImpinjModel) String() string {
	switch {
	case 2001001 <= i && i <= 2001004:
		i -= 2001001
		return _ImpinjModel_name_0[_ImpinjModel_index_0[i]:_ImpinjModel_index_0[i+1]]
	case 2001006 <= i && i <= 2001009:
		i -= 2001006
		return _ImpinjModel_name_1[_ImpinjModel_index_1[i]:_ImpinjModel_index_1[i+1]]
	case i == 2001052:
		return _ImpinjModel_name_2
	default:
		return "ImpinjModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
